import { useState, useEffect, useCallback } from 'react'
import { supabase } from './lib/supabase'
import NavBar          from './components/NavBar.jsx'
import AuthScreen      from './components/AuthScreen.jsx'
import WelcomeScreen   from './components/WelcomeScreen.jsx'
import FacultyScreen   from './components/FacultyScreen.jsx'
import QuizScreen      from './components/QuizScreen.jsx'
import ResultsScreen   from './components/ResultsScreen.jsx'

export default function App() {
  const [authUser,   setAuthUser]  = useState(undefined)  // undefined = loading, null = logged out
  const [careerData, setCareerData]= useState(null)        // real dataset JSON (or null)
  const [screen,     setScreen]   = useState('welcome')
  const [faculty,    setFaculty]  = useState(null)
  const [currentQ,   setCurrentQ] = useState(0)
  const [answers,    setAnswers]  = useState({})

  // Listen for auth state changes (handles page refresh too)
  useEffect(() => {
    supabase.auth.getSession().then(({ data }) => {
      setAuthUser(data.session?.user ?? null)
    })

    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
      setAuthUser(session?.user ?? null)
    })

    return () => subscription.unsubscribe()
  }, [])

  // Load real career dataset JSON (generated by process_dataset.py)
  useEffect(() => {
    fetch('/career_data.json')
      .then(r => r.ok ? r.json() : null)
      .then(data => {
        if (data?.careers) {
          setCareerData(data)
          console.log(`✅ Real career data loaded: ${Object.keys(data.careers).length} careers from ${data.meta?.total_records?.toLocaleString()} records`)
        }
      })
      .catch(() => {
        console.log('ℹ️ career_data.json not found — using built-in scoring. Run process_dataset.py to enable real-data mode.')
      })
  }, [])

  function goTo(s) {
    setScreen(s)
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  function selectFaculty(f) {
    setFaculty(f)
    document.documentElement.style.setProperty('--fac-color', f.color)
  }

  function startQuiz() {
    setCurrentQ(0)
    setAnswers({})
    goTo('quiz')
  }

  function answer(qId, value, type) {
    setAnswers(prev => {
      if (type === 'radio') return { ...prev, [qId]: value }
      const existing = prev[qId] || []
      const idx      = existing.indexOf(value)
      const updated  = idx > -1
        ? existing.filter(v => v !== value)
        : [...existing, value]
      if (!updated.length) {
        const { [qId]: _, ...rest } = prev
        return rest
      }
      return { ...prev, [qId]: updated }
    })
  }

  function nextQ() {
    const TOTAL = 6
    if (currentQ < TOTAL - 1) setCurrentQ(q => q + 1)
    else goTo('results')
  }

  function prevQ() {
    if (currentQ > 0) setCurrentQ(q => q - 1)
  }

  function restart() {
    setFaculty(null)
    setCurrentQ(0)
    setAnswers({})
    document.documentElement.style.setProperty('--fac-color', '#4f46e5')
    goTo('welcome')
  }

  // Still checking session
  if (authUser === undefined) {
    return (
      <div style={{ display:'flex', alignItems:'center', justifyContent:'center', minHeight:'100vh', color:'#64748b', fontSize:15 }}>
        Loading…
      </div>
    )
  }

  // Not authenticated → show auth screen
  if (authUser === null) {
    return <AuthScreen onAuth={setAuthUser} initialTab="register" />
  }

  // Authenticated
  const shared = { faculty, goTo }
  const userName  = authUser.user_metadata?.full_name || authUser.email
  const userEmail = authUser.email

  return (
    <>
      <NavBar faculty={faculty} userName={userName} onLogout={() => supabase.auth.signOut()} />

      {screen === 'welcome' && (
        <WelcomeScreen goTo={goTo} userName={userName} userEmail={userEmail} />
      )}
      {screen === 'faculty' && (
        <FacultyScreen {...shared} selectFaculty={selectFaculty} startQuiz={startQuiz} />
      )}
      {screen === 'quiz' && (
        <QuizScreen
          {...shared}
          currentQ={currentQ}
          answers={answers}
          answer={answer}
          nextQ={nextQ}
          prevQ={prevQ}
        />
      )}
      {screen === 'results' && (
        <ResultsScreen
          {...shared}
          user={{ name: userName, email: userEmail }}
          answers={answers}
          careerData={careerData}
          restart={restart}
        />
      )}
    </>
  )
}
